# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-03 13:00
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ContactDetail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(choices=[(b'Mr', b'Mr'), (b'Miss', b'Miss'), (b'Mrs', b'Mrs'), (b'Dr', b'Dr')], max_length=10, verbose_name=b'Title')),
                ('full_name', models.CharField(max_length=30, verbose_name=b'Full Name')),
                ('location', models.CharField(choices=[(b'United Kingdom', b'United Kingdom'), (b'Zambia', b'Zambia'), (b'Namibia', b'Namibia'), (b'Congo', b'Congo'), (b'Burundi', b'Burundi'), (b'Botswana', b'Botswana'), (b'Tanzania', b'Tanzania'), (b'Malawi', b'Malawi')], max_length=50, verbose_name=b'Location')),
                ('address', models.CharField(blank=True, max_length=300, verbose_name=b'Address (Optional)')),
                ('city', models.CharField(blank=True, max_length=300, verbose_name=b'City/Town')),
                ('postcode', models.CharField(blank=True, max_length=10, verbose_name=b'PostCode (Optional)')),
                ('telephone', models.CharField(blank=True, max_length=20, verbose_name=b'Phone')),
                ('email', models.CharField(max_length=100, verbose_name=b'Email')),
            ],
        ),
        migrations.CreateModel(
            name='Picture',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(null=True, upload_to=b'vehicle_images')),
            ],
        ),
        migrations.CreateModel(
            name='Vehicle',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ref', models.CharField(max_length=6, unique=True, verbose_name=b'Reference No (1 - 6 Characters Only)')),
                ('type', models.CharField(choices=[(b'TRUCK', b'TRUCK'), (b'MACHINERY & EQUIPS', b'MACHINERY & EQUIPMENT')], max_length=50, verbose_name=b'Type of Vehicle')),
                ('make', models.CharField(blank=True, choices=[(b'', b''), (b'Unknown', b'Unknown'), (b'ACURA', b'ACURA'), (b'ALFA', b'ALFA'), (b'ASTON', b'ASTON'), (b'AUDI', b'AUDI'), (b'BMW', b'BMW'), (b'Leyland DAF', b'Leyland DAF'), (b'ERF', b'ERF'), (b'FIAT', b'FIAT'), (b'Foden', b'Foden'), (b'FORD', b'FORD'), (b'GOLF', b'GOLF'), (b'HONDA', b'HONDA'), (b'Hyundai', b'Hyundai'), (b'IVECO', b'IVECO'), (b'MAZDA', b'MAZDA'), (b'MERCEDES-BENZ', b'MERCEDES-BENZ'), (b'MITSUBISHI', b'MITSUBISHI'), (b'NISSAN', b'NISSAN'), (b'RENAULT', b'RENAULT'), (b'SCANIA', b'SCANIA'), (b'TOYOTA', b'TOYOTA'), (b'VOLVO', b'VOLVO')], max_length=30, verbose_name=b'Make')),
                ('model', models.CharField(max_length=100, verbose_name=b'Model')),
                ('year', models.IntegerField(blank=True, null=True, verbose_name=b'Year (E.g. 1990)')),
                ('desc', models.TextField(max_length=400, verbose_name=b'Description')),
                ('showroom', models.CharField(blank=True, choices=[(b'Y', b'Yes'), (b'N', b'No')], default=b'N', max_length=1, verbose_name=b"In Zambia's Showroom")),
                ('status', models.CharField(blank=True, choices=[(b'A', b'Available'), (b'S', b'SOLD')], default=b'A', max_length=1, verbose_name=b'Status')),
                ('date_added', models.DateField(verbose_name=b'Date Added')),
                ('image', models.ImageField(null=True, upload_to=b'vehicle_images')),
            ],
            options={
                'ordering': ['date_added'],
            },
        ),
        migrations.AddField(
            model_name='picture',
            name='model',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='techmiya.Vehicle'),
        ),
    ]
